# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getA <- function(ALPHA1, ACHG, d_dyn1, d1, y, X, HH) {
    .Call('threshtvp_getA', PACKAGE = 'threshtvp', ALPHA1, ACHG, d_dyn1, d1, y, X, HH)
}

Mahalanobis <- function(x, center, cov) {
    .Call('threshtvp_Mahalanobis', PACKAGE = 'threshtvp', x, center, cov)
}

dmvnorm_arma <- function(x, mean, sigma, log = TRUE) {
    .Call('threshtvp_dmvnorm_arma', PACKAGE = 'threshtvp', x, mean, sigma, log)
}

sampleA <- function(ALPHA, A0, Q, Qpr, X, y, sig, d_dyn, d, omegas, Ystd, Xstd) {
    .Call('threshtvp_sampleA', PACKAGE = 'threshtvp', ALPHA, A0, Q, Qpr, X, y, sig, d_dyn, d, omegas, Ystd, Xstd)
}

dinvgamma <- function(x, a, b) {
    .Call('threshtvp_dinvgamma', PACKAGE = 'threshtvp', x, a, b)
}

get_moving_incl <- function(ALPHA1, Atilde1, XX, YY, HH, Achg1, d1, scale, scale0, perm2, a0, a1) {
    .Call('threshtvp_get_moving_incl', PACKAGE = 'threshtvp', ALPHA1, Atilde1, XX, YY, HH, Achg1, d1, scale, scale0, perm2, a0, a1)
}

get_variable_incl <- function(ALPHA1, ACHG, XX, YY, HH, dd, d_dyn1, scale, perm1) {
    .Call('threshtvp_get_variable_incl', PACKAGE = 'threshtvp', ALPHA1, ACHG, XX, YY, HH, dd, d_dyn1, scale, perm1)
}

KF <- function(y, Z, Ht, Qtt, m, p, t, B0, V0) {
    .Call('threshtvp_KF', PACKAGE = 'threshtvp', y, Z, Ht, Qtt, m, p, t, B0, V0)
}

