# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_threshold <- function(Achg1, SIGMAS1, SIGMAS2, threshgrid, Aapprox) {
    .Call('_threshtvp_get_threshold', PACKAGE = 'threshtvp', Achg1, SIGMAS1, SIGMAS2, threshgrid, Aapprox)
}

dinvgamma <- function(x, a, b) {
    .Call('_threshtvp_dinvgamma', PACKAGE = 'threshtvp', x, a, b)
}

KF <- function(y, Z, Ht, Qtt, m, p, t, B0, V0) {
    .Call('_threshtvp_KF', PACKAGE = 'threshtvp', y, Z, Ht, Qtt, m, p, t, B0, V0)
}

get_lik <- function(y, Z, Ht, Qtt, m, p, t, B0, V0) {
    .Call('_threshtvp_get_lik', PACKAGE = 'threshtvp', y, Z, Ht, Qtt, m, p, t, B0, V0)
}

KF_fast <- function(y, Z, Ht, Qtt, m, p, t, B0, V0) {
    .Call('_threshtvp_KF_fast', PACKAGE = 'threshtvp', y, Z, Ht, Qtt, m, p, t, B0, V0)
}

KF_MH <- function(y, Z, Ht, Qtt, m, p, t, B0, V0) {
    .Call('_threshtvp_KF_MH', PACKAGE = 'threshtvp', y, Z, Ht, Qtt, m, p, t, B0, V0)
}

